// MYRAA AI OS — Tool Registry (§11)
// Rule: Myraa -> Tool Registry -> Connector -> API Adapter -> Permission Check -> External API.
// Every tool: id, description, input/output schema, permissions, risk, connector, timeout, retry, audit.

export type RiskLevel = 'READ_ONLY' | 'SAFE_WRITE' | 'DESTRUCTIVE' | 'CRITICAL_SYSTEM';

export interface ToolDef {
  id: string;               // e.g. myraa.weather.get
  description: string;
  connector: string;        // connector id (packages/api-registry/connectors/*) or 'tauri-core' | 'local'
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  permissions: string[];
  risk: RiskLevel;
  timeoutMs: number;
  retry: { max: number; backoffMs: number };
  auditEvent: string;
  voiceEnabled: boolean;
}

export const TOOL_REGISTRY: ToolDef[] = [
  { id: 'myraa.web.search', description: 'Deep web research (existing DuckDuckGo + Wikipedia synthesis).', connector: 'web-research', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['network'], risk: 'READ_ONLY', timeoutMs: 20000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.web.search', voiceEnabled: true },
  { id: 'myraa.weather.get', description: 'Current weather + forecast for a location.', connector: 'weather', inputSchema: { type: 'object', properties: { location: { type: 'string' } }, required: ['location'] }, outputSchema: { type: 'object' }, permissions: ['network', 'location'], risk: 'READ_ONLY', timeoutMs: 10000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.weather.get', voiceEnabled: true },
  { id: 'myraa.currency.convert', description: 'Read-only FX conversion with disclaimer. No transactions.', connector: 'currency', inputSchema: { type: 'object', properties: { amount: { type: 'number' }, from: { type: 'string' }, to: { type: 'string' } }, required: ['amount', 'from', 'to'] }, outputSchema: { type: 'object' }, permissions: ['network'], risk: 'READ_ONLY', timeoutMs: 10000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.currency.convert', voiceEnabled: true },
  { id: 'myraa.github.repo_list', description: 'List repos in allow-list scope (read).', connector: 'github', inputSchema: { type: 'object', properties: {} }, outputSchema: { type: 'object' }, permissions: ['github.read'], risk: 'READ_ONLY', timeoutMs: 15000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.github.repo_list', voiceEnabled: true },
  { id: 'myraa.github.repo_tree', description: 'Read a repository file tree (read).', connector: 'github', inputSchema: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, branch: { type: 'string' } }, required: ['owner', 'repo'] }, outputSchema: { type: 'object' }, permissions: ['github.read'], risk: 'READ_ONLY', timeoutMs: 20000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.github.repo_tree', voiceEnabled: true },
  { id: 'myraa.github.read_file', description: 'Read a single file from a repo (read).', connector: 'github', inputSchema: { type: 'object', properties: { owner: { type: 'string' }, repo: { type: 'string' }, path: { type: 'string' }, ref: { type: 'string' } }, required: ['owner', 'repo', 'path'] }, outputSchema: { type: 'object' }, permissions: ['github.read'], risk: 'READ_ONLY', timeoutMs: 20000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.github.read_file', voiceEnabled: true },
  { id: 'myraa.github.search_code', description: 'Search code within allowed repos.', connector: 'github', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['github.read'], risk: 'READ_ONLY', timeoutMs: 15000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.github.search_code', voiceEnabled: true },
  { id: 'myraa.github.create_branch', description: 'Create branch (write, needs confirmation).', connector: 'github', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, branch: { type: 'string' } }, required: ['repo', 'branch'] }, outputSchema: { type: 'object' }, permissions: ['github.write'], risk: 'SAFE_WRITE', timeoutMs: 15000, retry: { max: 1, backoffMs: 1000 }, auditEvent: 'tool.github.create_branch', voiceEnabled: true },
  { id: 'myraa.github.create_pr', description: 'Create PR (write, needs confirmation).', connector: 'github', inputSchema: { type: 'object', properties: { repo: { type: 'string' }, head: { type: 'string' }, base: { type: 'string' } }, required: ['repo', 'head', 'base'] }, outputSchema: { type: 'object' }, permissions: ['github.write'], risk: 'SAFE_WRITE', timeoutMs: 15000, retry: { max: 1, backoffMs: 1000 }, auditEvent: 'tool.github.create_pr', voiceEnabled: true },
  { id: 'myraa.gmail.search', description: 'Search Gmail (read).', connector: 'gmail', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['gmail.read'], risk: 'READ_ONLY', timeoutMs: 15000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.gmail.search', voiceEnabled: true },
  { id: 'myraa.gmail.send', description: 'Send email — ALWAYS confirmation modal.', connector: 'gmail', inputSchema: { type: 'object', properties: { to: { type: 'string' }, subject: { type: 'string' }, body: { type: 'string' } }, required: ['to', 'subject', 'body'] }, outputSchema: { type: 'object' }, permissions: ['gmail.send'], risk: 'SAFE_WRITE', timeoutMs: 15000, retry: { max: 1, backoffMs: 1000 }, auditEvent: 'tool.gmail.send', voiceEnabled: true },
  { id: 'myraa.calendar.get_events', description: 'Read calendar events.', connector: 'google-calendar', inputSchema: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' } } }, outputSchema: { type: 'object' }, permissions: ['calendar.read'], risk: 'READ_ONLY', timeoutMs: 10000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.calendar.get', voiceEnabled: true },
  { id: 'myraa.calendar.get_holidays', description: 'Public holidays (Nager.Date, no key).', connector: 'holidays', inputSchema: { type: 'object', properties: { country: { type: 'string' }, year: { type: 'number' } }, required: ['country'] }, outputSchema: { type: 'object' }, permissions: ['network'], risk: 'READ_ONLY', timeoutMs: 10000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.calendar.holidays', voiceEnabled: true },
  { id: 'myraa.drive.search', description: 'Search Drive files (read).', connector: 'google-drive', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['drive.read'], risk: 'READ_ONLY', timeoutMs: 15000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.drive.search', voiceEnabled: true },
  { id: 'myraa.news.search', description: 'News via RSS (no key). Cache + honor freshness.', connector: 'news', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['network'], risk: 'READ_ONLY', timeoutMs: 15000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.news.search', voiceEnabled: true },
  { id: 'myraa.news.headlines', description: 'Curated RSS headlines from a trusted source (BBC, Ars, Verge, NPR, Wired, TechCrunch, Hindu).', connector: 'news', inputSchema: { type: 'object', properties: { source: { type: 'string' }, limit: { type: 'number' } } }, outputSchema: { type: 'object' }, permissions: ['network'], risk: 'READ_ONLY', timeoutMs: 15000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.news.headlines', voiceEnabled: true },
  { id: 'myraa.knowledge.book_lookup', description: 'Book lookup (Open Library).', connector: 'knowledge-books', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['network'], risk: 'READ_ONLY', timeoutMs: 10000, retry: { max: 2, backoffMs: 1000 }, auditEvent: 'tool.books.lookup', voiceEnabled: true },
  { id: 'myraa.system.open_app', description: 'Open app via allow-list alias (existing Tauri/desktopAutomation).', connector: 'tauri-core', inputSchema: { type: 'object', properties: { alias: { type: 'string' } }, required: ['alias'] }, outputSchema: { type: 'object' }, permissions: ['system.launch'], risk: 'SAFE_WRITE', timeoutMs: 8000, retry: { max: 1, backoffMs: 500 }, auditEvent: 'tool.system.open_app', voiceEnabled: true },
  { id: 'myraa.system.file_operation', description: 'FS op via existing Tauri FS gate (CONFIRM outside workspace).', connector: 'tauri-core', inputSchema: { type: 'object', properties: { op: { type: 'string' }, path: { type: 'string' } }, required: ['op', 'path'] }, outputSchema: { type: 'object' }, permissions: ['fs'], risk: 'DESTRUCTIVE', timeoutMs: 15000, retry: { max: 1, backoffMs: 500 }, auditEvent: 'tool.system.file', voiceEnabled: true },
  { id: 'myraa.files.search', description: 'Unified search: local files + memory + knowledge + connectors.', connector: 'universal-search', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] }, outputSchema: { type: 'object' }, permissions: ['fs.read', 'memory.read'], risk: 'READ_ONLY', timeoutMs: 20000, retry: { max: 1, backoffMs: 500 }, auditEvent: 'tool.files.search', voiceEnabled: true },
];

export function getTool(id: string): ToolDef | undefined { return TOOL_REGISTRY.find((t) => t.id === id); }
export function toolsForConnector(connector: string): ToolDef[] { return TOOL_REGISTRY.filter((t) => t.connector === connector); }
